name       : irrlichtmt
version    : 1.9.0.7
release    : 10
source     :
    - https://github.com/minetest/irrlicht/archive/refs/tags/1.9.0mt7.tar.gz : c12cdbd4a852e1e6ebf7ba22789aa057a1a7f2d585dd81a2412a62f57a0e2619
license    : Zlib
component  : multimedia
summary    : Realtime 3D Engine
description: |
    The Irrlicht Engine is an open source high performance realtime 3D engine written in C++. It is completely cross-platform, using D3D, OpenGL and its own software renderers, and has all of the state-of-the-art features which can be found in commercial 3d engines
replaces   :
    - irrlicht
    - devel :
        - irrlicht-devel
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(xi)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
