name       : irrlichtmt
version    : 1.9.0.4
release    : 7
source     :
    - https://github.com/minetest/irrlicht/archive/refs/tags/1.9.0mt4.tar.gz : a0e2e5239ebca804adf54400ccaacaf228ec09223cfb2e1daddc9bf2694176e6
license    : Zlib
component  : multimedia
summary    : Realtime 3D Engine
description: |
    The Irrlicht Engine is an open source high performance realtime 3D engine written in C++. It is completely cross-platform, using D3D, OpenGL and its own software renderers, and has all of the state-of-the-art features which can be found in commercial 3d engines
replaces   :
    - irrlicht
    - devel:
        - irrlicht-devel
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(xxf86vm)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
