name       : irrlicht
version    : 1.8.4
release    : 6
source     :
    - http://downloads.sourceforge.net/irrlicht/irrlicht-1.8.4.zip : f42b280bc608e545b820206fe2a999c55f290de5c7509a02bdbeeccc1bf9e433
license    : Zlib
component  : multimedia
summary    : Realtime 3D Engine
description: |
    The Irrlicht Engine is an open source high performance realtime 3D engine written in C++. It is completely cross-platform, using D3D, OpenGL and its own software renderers, and has all of the state-of-the-art features which can be found in commercial 3d engines
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpng)
    - pkgconfig(xxf86vm)
    - bzip2-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-system-libraries.patch
    %patch -p1 < $pkgfiles/irrlicht-1.8.4-no-sysctl-on-linux.patch
build      : |
    %make -C source/Irrlicht sharedlib NDEBUG=1
install    : |
    install -d $installdir/usr/include/irrlicht
    install -Dm00644 include/* $installdir/usr/include/irrlicht

    install -Dm00644 lib/Linux/libIrrlicht.so.${version} $installdir/usr/lib/libIrrlicht.so.${version}

    ln -s /usr/lib/libIrrlicht.so.${version} $installdir/usr/lib/libIrrlicht.so
    ln -s /usr/lib/libIrrlicht.so.${version} $installdir/usr/lib/libIrrlicht.so.1.8
